### ISSUE TITLE
When modifying an entry/pet on the main page, the model "Save" button does not work

### ISSUE THREAD

**Issue by Morotai** [Adzz/petacular#1]
When I try to modify an entry, the Save button does not close the form and the item is not updated. Also, had to modify the user name and password as well as the port number to make it work with my Postgress local db on dev.exs. 

Here is the error message:

`[error] GenServer #PID<0.607.0> terminating
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * pets_pkey (unique_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `unique_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset has not defined any constraint.

    (ecto 3.9.5) lib/ecto/repo/schema.ex:795: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir 1.15.5) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ecto 3.9.5) lib/ecto/repo/schema.ex:780: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto 3.9.5) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
    (ecto 3.9.5) lib/ecto/repo/schema.ex:369: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (petacular 0.1.0) lib/petacular_web/pages/home_live.ex:107: PetacularWeb.HomeLive.handle_event/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:401: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) c:/Users/rafae/source/repos/petacular/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:221: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F5S063K3x7ywtQBB", event: "event", payload: %{"event" => "edit_pet", "type" => "form", "value" => "pet%5Bid%5D=4&pet%5Bname%5D=Caballo"}, ref: "21", join_ref: "18"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F5S063K3x7ywtQBB", endpoint: PetacularWeb.Endpoint, view: PetacularWeb.HomeLive, parent_pid: nil, root_pid: #PID<0.607.0>, router: PetacularWeb.Router, assigns: %{__changed__: %{}, flash: %{}, pets: [%Petacular.Pet{__meta__: #Ecto.Schema.Metadata<:loaded, "pets">, id: 1, name: "Dog", preferences: #Ecto.Association.NotLoaded<association :preferences is not loaded>, inserted_at: ~N[2023-11-05 10:58:18], updated_at: ~N[2023-11-05 10:58:18]}, %Petacular.Pet{__meta__: #Ecto.Schema.Metadata<:loaded, "pets">, id: 2, name: "Cat", preferences: #Ecto.Association.NotLoaded<association :preferences is not loaded>, inserted_at: ~N[2023-11-05 10:58:21], updated_at: ~N[2023-11-05 10:58:21]}, %Petacular.Pet{__meta__: #Ecto.Schema.Metadata<:loaded, "pets">, id: 3, name: "Burro", preferences: #Ecto.Association.NotLoaded<association :preferences is not loaded>, inserted_at: ~N[2023-11-05 10:58:26], updated_at: ~N[2023-11-05 10:58:26]}, %Petacular.Pet{__meta__: #Ecto.Schema.Metadata<:loaded, "pets">, id: 4, name: "Caballo", preferences: #Ecto.Association.NotLoaded<association :preferences is not loaded>, inserted_at: ~N[2023-11-05 10:58:44], updated_at: ~N[2023-11-05 10:58:44]}], edit_form: %Phoenix.HTML.Form{source: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #Petacular.Pet<>, valid?: true>, impl: Phoenix.HTML.FormData.Ecto.Changeset, id: "pet", name: "pet", data: %Petacular.Pet{__meta__: #Ecto.Schema.Metadata<:loaded, "pets">, id: 4, name: "Caballo", preferences: #Ecto.Association.NotLoaded<association :preferences is not loaded>, inserted_at: ~N[2023-11-05 10:58:44], updated_at: ~N[2023-11-05 10:58:44]}, hidden: [id: 4], params: %{}, errors: [], options: [method: "put"], index: nil, action: nil}, create_form: %Phoenix.HTML.Form{source: #Ecto.Changeset<action: nil, changes: %{}, errors: [name: {"can't be blank", [validation: :required]}], data: #Petacular.Pet<>, valid?: false>, impl: Phoenix.HTML.FormData.Ecto.Changeset, id: "pet", name: "pet", data: %Petacular.Pet{__meta__: #Ecto.Schema.Metadata<:built, "pets">, id: nil, name: nil, preferences: #Ecto.Association.NotLoaded<association :preferences is not loaded>, inserted_at: nil, updated_at: nil}, hidden: [], params: %{}, errors: [], options: [method: "post"], index: nil, action: nil}, live_action: nil}, transport_pid: #PID<0.596.0>, ...>, components: {%{}, %{}, 1}, topic: "lv:phx-F5S063K3x7ywtQBB", serializer: Phoenix.Socket.V2.JSONSerializer, join_ref: "18", upload_names: %{}, upload_pids: %{}}
[debug] MOUNT PetacularWeb.HomeLive
  Parameters: %{}
  Session: %{"_csrf_token" => "PCKoa_a-2McHL8gOI-apkpef"}
[debug] QUERY OK source="pets" db=2.6ms idle=1686.7ms
SELECT p0."id", p0."name", p0."inserted_at", p0."updated_at" FROM "pets" AS p0 []`

**Comment by Adzz** [comment]
Hello! Apologies for the late reply it never occurred to me someone might raise an issue here, but you are entirely correct I have ham fisted the example nicely.

> had to modify the user name and password as well as the port number to make it work with my Postgress local db on dev.exs.

That is expected, though I should probably have used the default `postgres` user and password to make things simple for everyone. 

> When I try to modify an entry, the Save button does not close the form and the item is not updated


Right you are, the issue stems from me using `Repo.insert` instead of `Repo.update` - how is that for a typo. It's possible I was going to upsert and just forgot to use the `:on_conflict` and `:conflict_target` options.

Nevertheless I have made a new commit here  ad5c4e15c7c5efdcd7d5aef1242cfc34b0fdc2dc

I hope it wasn't too confusing for you.
